# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "bilibili"
    name       = "Bilibili"
    url        = "https://space.bilibili.com"

    [social.params]
        icon = "brand-bilibili"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/qiuyuxc"

    [social.params]
        icon = "brand-github"
