mainSections = ["post"]
rssFullContent = true
favicon        = "img/favicon.png"

# 站点描述（用于 meta description 和首页）
description = "记录个人随笔与技术实践的独立站点，主要分享折腾过程中的想法与经验."
keywords    = ["Firefly", "Fuwari", "Astro", "ACGN", "博客", "技术博客", "静态博客"]

# 站点展示名（侧栏显示，不填则用 config.toml 的 title）
siteName = "Kukie"

SortBy = "default"

[footer]
    since      = 2024
    customText = ""

[dateFormat]
    published   = "2006-01-02"
    lastUpdated = "2006-01-02"

[sidebar]
    emoji    = "🍥"
    subtitle = "没活了"
    avatar   = "img/avatar.jpg"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

[comments]
    enabled  = true
    provider = "giscus"

    [comments.giscus]
        repo             = "qiuyuxc/fuwari-giscus"
        repoID           = "R_kgDOQ8yzoA"
        category         = "Announcements"
        categoryID       = "DIC_kwDOQ8yzoM4C1JX1"
        mapping          = "pathname"
        strict           = "0"
        reactionsEnabled = "1"
        emitMetadata     = "0"
        inputPosition    = "top"
        lightTheme       = "light"
        darkTheme        = "dark"
        lang             = "zh-CN"
        loading          = "lazy"
